name: Makefile CI

on:
  push:
    branches: [ "uvite" ]
  pull_request:
    branches: [ "uvite" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: ./build.sh

